### PR TITLE
Commented out print statement in parse()

### PR DESCRIPTION
**Pull request by robmcmullen**
looks like a debug print got left in.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks! I thought I had gotten all those :-)

**Comment by ChrisBarker-NOAA** [comment]
Can you think of a way to do an auto-test (that could be run in a CI) to make sure that there are no wayward prints around?

One problem is that I'm using pytest to run and test the code, but it swallows stdout when there isn't an error.

**Comment by robmcmullen** [comment]
Isn't print is just a regular, plain-ol' function now in python 3? How about redefining it to raise a RuntimeError during tests?

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- yes, it is, but it's also a builtin -- but you could probably mock it.

Not sure when I'll get around to trying that, maybe next time it bites me :-)

**Pull request merged**
